version: '2'
services:
  web:
    build: .
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo16:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    ports:
      - "5432:5432"
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo16-db:/var/lib/postgresql/data/pgdata
volumes:
  odoo16:
  odoo16-db:

  # me8e-s3ix-zisv


